name: Jira-Checks
description: I will verify your jira ticket
inputs:
  token:
    description: Provide Jira Token
    required: true
    default: null
  project_id:
    description: Provide Jira Project Id
    required: true
    default: null
  path:
    description: Path to your logic file
    required: true
    default: null
  GITHUB_TOKEN:
    description: Path to your logic file
    required: true
    default: null
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
outputs:
  new-version:
    description: Output on the basis of checks provided
runs:
  using: node12
  main: action/index.js